CREATE TABLE BUKU (
    ID_BUKU INT PRIMARY KEY,
    JUDUL VARCHAR(255) NOT NULL,
    ID_PENULIS INT,
    ID_KATEGORI INT,
    TAHUN_TERBIT INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_PENULIS) REFERENCES PENULIS(ID_PENULIS),
    FOREIGN KEY (ID_KATEGORI) REFERENCES KATEGORI(ID_KATEGORI)
);

CREATE TABLE PENULIS (
    ID_PENULIS INT PRIMARY KEY,
    NAMA_PENULIS VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE KATEGORI (
    ID_KATEGORI INT PRIMARY KEY,
    NAMA_KATEGORI VARCHAR(255) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP

);

SELECT BUKU.JUDUL, BUKU.TAHUN_TERBIT, PENULIS.NAMA_PENULIS
FROM BUKU
JOIN PENULIS ON BUKU.ID_PENULIS = PENULIS.ID_PENULIS;

SELECT BUKU.JUDUL, PENULIS.NAMA_PENULIS
FROM BUKU
JOIN PENULIS ON BUKU.ID_PENULIS = PENULIS.ID_PENULIS
WHERE BUKU.ID_KATEGORI = (SELECT ID_KATEGORI FROM KATEGORI WHERE NAMA_KATEGORI = 'NamaKategori');



